{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
{{ include "spaceone.labels" . | indent 4 }}
    spaceone.service: {{ .Values.name }}
  name: {{ .Values.name }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
spec:
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      spaceone.service: {{ .Values.name }}
  template:
    metadata:
      annotations:
        spaceone.deployment.tool: helm
      labels:
{{ include "spaceone.labels" . | indent 8 }}
        spaceone.service: {{ .Values.name }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.gracePeriod }}
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image.name }}:{{ .Values.image.version }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: timezone
              mountPath: /etc/localtime

{{- if .Values.sidecar }}
{{- toYaml .Values.sidecar | nindent 8 }}
{{- end }}

{{- if .Values.global.frontend.sidecar }}
{{- toYaml .Values.global.frontend.sidecar | nindent 8 }}
{{- end }}

      volumes:
{{- if .Values.volumes }}
{{- toYaml .Values.volumes | nindent 8 }}
{{- end }}

{{- if .Values.global.frontend.volumes }}
{{- toYaml .Values.global.frontend.volumes | nindent 8 }}
{{- end }}

{{- if .Values.pod.spec }}
{{- toYaml .Values.pod.spec | nindent 6 }}
{{- end }}

{{- end }}
